---
- name: initialize prechecks
  block:
    - name: begin precheck
      debug:
        msg:  "######################################## TAKING PRECHECK LOGS ########################################################.stdout###"
  tags:
    - pre
- name: verify hostname
  block:
    - name: read hostname
      shell: hostname
      register: hostname
    - name: set fact [hostname]
      set_fact:
        results_pre: '{{ results_pre | combine({"hostname": " ".join(hostname.stdout_lines)|quote }) }}'
    - name: write hostname
      debug:
        msg: "{{ hostname.stdout }}"
  tags:
    - pre
- name: distribution info
  block:
    - name: get uname output
      shell: uname -r
      register: uname
    - name: set uname fact
      set_fact:
        results_pre: '{{ results_pre|combine({"uname": " ".join(uname.stdout_lines)|quote }) }}'
    - name: dump uname output
      debug:
        msg: "{{ uname.stdout }}"
  tags:
    - pre
- name: get sysconfig networking info
  block:
    - name: read network cfg file
      shell:  "cat /etc/sysconfig/network"
      ignore_errors: true
      register: syscfg_net
    - name: set fact syscfg network
      set_fact:
        results_pre: '{{ results_pre|combine({"syscfg_net": " ".join(syscfg_net.stdout_lines)|quote }) }}'
    - name: write syscfg network data
      debug:
        msg: "{{ syscfg_net.stdout }}"
  tags:
    - pre
- name: check routes info
  block:
    - name: grab routes
      shell: "route -n | sort"
      register: route
    - name: set fact routes
      set_fact:
        results_pre: '{{ results_pre|combine({"route": " ".join(route.stdout_lines)|quote }) }}'
    - name: log routes info
      debug:
        msg: "{{ route.stdout }}"
  tags:
    - pre
- name: Find the disk utilization
  block:
    - name: get df output
      shell: "df -hP | awk '{print $1 \" \" $6}' | sort"
      register: df
    - name: set df fact
      set_fact:
        results_pre: '{{ results_pre|combine({"df": " ".join(df.stdout_lines)|quote }) }}'
    - name: dump df output
      debug:
        msg: "{{ df.stdout }}"
  tags:
    - pre
- name: retrieve mounts info
  block:
    - name: get mount output
      shell: "mount -l | sort"
      register: mounts
    - name: set fact mounts
      set_fact:
        results_pre: '{{ results_pre|combine({"mounts": " ".join(mounts.stdout_lines)|quote }) }}'
    - name: dump mounts info
      debug:
        msg: "{{ mounts.stdout }}"
  tags:
    - pre
- name: get fdisks info
  block:
    - name: get fdisk output
      shell: "fdisk -l"
      register: fdisk
    - name: set fact fdisk
      set_fact:
        results_pre: '{{ results_pre|combine({"fdisk": " ".join(fdisk.stdout_lines)|quote }) }}'
    - name: write fdisk output
      debug:
        msg: "{{ fdisk.stdout }}"
  tags:
    - pre
- name: retrieve lsblk info
  block:
    - name: get lsblk output
      shell: "lsblk"
      register: lsblk
    - name: set fact lsblk
      set_fact:
        results_pre: '{{ results_pre|combine({"lsblk": " ".join(lsblk.stdout_lines)|quote }) }}'
    - name: dump lsblk output
      debug:
        msg: "{{ lsblk.stdout }}"
  tags:
    - pre
- name: retrieve lvs info
  block:
    - name: get lvs output
      shell: "lvs | sort"
      register: lvs
    - name: set fact lvs
      set_fact:
        results_pre: '{{ results_pre|combine({"lvs": " ".join(lvs.stdout_lines)|quote }) }}'
    - name: write lvs info
      debug:
        msg: "{{ lvs.stdout }}"
  tags:
    - pre
- name: read iptables service status
  block:
    - name: get sysctl iptables services status
      shell: "service iptables status"
      ignore_errors: true
      register: iptables
    - name: set fact iptables
      set_fact:
        results_pre: '{{ results_pre|combine({"iptables": " ".join(iptables.stdout_lines)|quote }) }}'
    - name: write iptables service status
      debug:
        msg: "{{ iptables.stdout }}"
  tags:
    - pre
- name: read firewalld service status
  block:
    - name: get iptables sysctl status
      shell: "service firewalld status"
      ignore_errors: true
      register: firewalld
    - name: set fact firewalld
      set_fact:
        results_pre: '{{ results_pre|combine({"firewalld": " ".join(firewalld.stdout_lines)|quote }) }}'
    - name: write firewlld service status
      debug:
        msg: "{{ firewalld.stdout }}"
  tags:
    - pre
- name: read sssd service status
  block:
    - name: get sysctl sssd service status
      shell: "systemctl status sssd | grep -i active"
      ignore_errors: true
      register: sssd
    - name: set fact sssd
      set_fact:
        results_pre: '{{ results_pre|combine({"sssd": " ".join(sssd.stdout_lines)|quote }) }}'
    - name: write sysctl sssd service status
      debug:
        msg: "{{ sssd.stdout }}"
  tags:
    - pre
- name: get internet interfaces info
  block:
    - name: retrieve ip addr output
      shell: "ip addr | awk '/^[0-9]+:/ {sub(/:/,\"\",$2); iface=$2 } /^[[:space:]]*inet / {split($2, a, \"/\"); print iface\" : \"a[1]}' | sort"
      register: ipa
    - name: set fact ip address
      set_fact:
        results_pre: '{{ results_pre|combine({"ipaddress": " ".join(ipa.stdout_lines)|quote }) }}'
    - name: dump ip addr info
      debug:
        msg: "{{ ipa.stdout }}"
  tags:
    - pre
